/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ktkun
 */
public class DangNhap extends javax.swing.JFrame {
    private static final String FILE_NAME = "account";

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txt_tk.setBackground(new java.awt.Color(0,0,0,1));
        txt_pass.setBackground(new java.awt.Color(0,0,0,1));
        setUndecorated(true);
        setOpacity(0.0f);
        loadUserData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eye_lock = new javax.swing.JLabel();
        eye_open = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        btn_login = new javax.swing.JButton();
        txt_tk = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng Nhập");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 358, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tài Khoản");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 218, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật Khẩu");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 216, 247, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" ____________________________________________");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 247, -1));

        eye_lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Images/eye_lock.png"))); // NOI18N
        eye_lock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_lockMouseClicked(evt);
            }
        });
        jPanel1.add(eye_lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 37, -1));

        eye_open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Images/eye_open.png"))); // NOI18N
        eye_open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_openMouseClicked(evt);
            }
        });
        jPanel1.add(eye_open, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 37, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_____________________________________");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 188, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Images/icons8-user-32.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 37, -1));

        check.setText("Nhớ Mật Khẩu");
        jPanel1.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 286, 138, -1));

        btn_login.setText("Đăng Nhập");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 285, -1, -1));

        txt_tk.setFont(txt_tk.getFont().deriveFont(txt_tk.getFont().getSize()+2f));
        txt_tk.setForeground(new java.awt.Color(255, 255, 255));
        txt_tk.setBorder(null);
        jPanel1.add(txt_tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, 30));

        txt_pass.setFont(txt_pass.getFont().deriveFont(txt_pass.getFont().getSize()+2f));
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass.setBorder(null);
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 200, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 20, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 380));

        setSize(new java.awt.Dimension(385, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eye_lockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_lockMouseClicked
        // TODO add your handling code here:
        txt_pass.setEchoChar((char)0);
        eye_lock.setVisible(false);
        eye_lock.setEnabled(false);
        
        eye_open.setVisible(true);
        eye_open.setEnabled(true);
    }//GEN-LAST:event_eye_lockMouseClicked

    private void eye_openMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_openMouseClicked
        // TODO add your handling code here:
        txt_pass.setEchoChar((char)8226);
        eye_lock.setVisible(true);
        eye_lock.setEnabled(true);
        
        eye_open.setVisible(false);
        eye_open.setEnabled(false);
    }//GEN-LAST:event_eye_openMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        new Thread(new Runnable() {
            public void run() {
                for(double i = 0.0; i <= 1.0; i += 0.1) {
                    float f = (float) i;
                    try {
                        // Đặt độ mờ của JFrame trên EDT
                        SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                setOpacity(f);
                            }
                        });
                        Thread.sleep(50);
                    } catch(InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
    }//GEN-LAST:event_formWindowOpened

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String user=txt_tk.getText();
        char[] passwordChars = txt_pass.getPassword();
        String pass = new String(passwordChars);
    
        if(user.equals("Admin") && pass.equals("123")){
            this.setVisible(false);
            Menu mn = new Menu();
            mn.setVisible(true);
            
            if(check.isSelected()){
                saveUserData();
            }else{
                clearUserData();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Tài Khoản Hoặc Mật Khẩu Không Đúng !!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_loginActionPerformed
private void loadUserData() {
    File file = new File(FILE_NAME);
    if (!file.exists()) {
        clearUserData(); // Xóa dữ liệu nếu tệp tin không tồn tại
        return;
    }
    
    try (BufferedReader br = new BufferedReader(new FileReader(FILE_NAME))) {
        String username = br.readLine();
        String password = br.readLine();
        if (username != null && password != null) {
            txt_tk.setText(username);
            txt_pass.setText(password);
            check.setSelected(true);
        }
    } catch (IOException e) {
        // Xử lý lỗi khi đọc tệp tin
        e.printStackTrace();
    }
}
    private void saveUserData() {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(FILE_NAME))) {
            bw.write(txt_tk.getText());
            bw.newLine();
            bw.write(new String(txt_pass.getPassword()));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void clearUserData() {
        File file = new File(FILE_NAME);
        if (file.exists()) {
            file.delete();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            // Tạo tệp tin "account" nếu nó không tồn tại
            File file = new File(FILE_NAME);
            if (!file.exists()) {
                file.createNewFile();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JCheckBox check;
    private javax.swing.JLabel eye_lock;
    private javax.swing.JLabel eye_open;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_tk;
    // End of variables declaration//GEN-END:variables
}
