/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import DB.DBManager;
import DB.DataBase;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ktkun
 */
public class ThayDoiGia extends javax.swing.JFrame {
    private final Map<String,String> spMap = new HashMap<>();
    /**
     * Creates new form ThayDoiGia
     */
    public ThayDoiGia() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        loadcb();
        updateCB();
    }
    private void loadcb(){
        try{
        String sql="select ma_sp,ten_sp from SanPham";
        ResultSet rs = DBManager.GetData(sql);
        
        cb_msp.removeAllItems();
        cb_tsp.removeAllItems();
        spMap.clear();
        
        while(rs.next()){
            
            String ma=rs.getString("ma_sp");
            String ten=rs.getString("ten_sp");
            
            cb_msp.addItem(ma);
            cb_tsp.addItem(ten);     
            spMap.put(ma, ten);
        }
        rs.close();
        }catch(SQLException ex){
            Logger.getLogger(SanPham.class.getName()).log(Level.SEVERE, null, ex);
        }finally {
            DataBase db = new DataBase();
            db.Disconnect(); 
        }
        
    }
    private void updateCB() {
    cb_msp.addActionListener(e -> {
        String Masp = (String) cb_msp.getSelectedItem();
        if (Masp != null) {
            cb_tsp.setSelectedItem(spMap.get(Masp));
        }
    });
    
    cb_tsp.addActionListener(e -> {
        String Tensp = (String) cb_tsp.getSelectedItem();
        if (Tensp != null) {
            for (Map.Entry<String, String> entry : spMap.entrySet()) {
                if (entry.getValue().equals(Tensp)) {
                    cb_msp.setSelectedItem(entry.getKey());
                    break;
                }
            }
        }
    });
}
    private long getDg(String masp){
        String sql ="select dg from hdn where ma_sp='"+masp+"'";
        ResultSet rs = DBManager.GetData(sql);
        long dg=0;
        try{
            while(rs.next()){
                dg=rs.getInt("dg");
            }
        }catch(SQLException e){
            Logger.getLogger(PhieuNhap.class.getName()).log(Level.SEVERE, null, e);
        }finally {
            DataBase db = new DataBase();
            db.Disconnect(); 
        }
        return dg;
        
    }
    private boolean kt_tt(String masp) {
        DataBase db = new DataBase();
        try {
            db.Connect();
            String sql = "SELECT COUNT(*) FROM hdn WHERE ma_sp='" + masp + "'";
            ResultSet rs = db.GetData(sql);
            if (rs.next()) {
                int count = rs.getInt(1);
                return count > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            db.Disconnect(); // Đóng kết nối trong khối finally
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_tang = new javax.swing.JButton();
        btn_giam = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_pt = new javax.swing.JTextField();
        cb_msp = new javax.swing.JComboBox<>();
        cb_tsp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên Sản Phẩm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã Sản Phẩm");

        btn_tang.setText("Tăng Giá");
        btn_tang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tangActionPerformed(evt);
            }
        });

        btn_giam.setText("Giảm Giá");
        btn_giam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giamActionPerformed(evt);
            }
        });

        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Phần Trăm (%) :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_tang, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_giam, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_pt)
                            .addComponent(cb_msp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_tsp, 0, 108, Short.MAX_VALUE))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_msp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_tsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_giam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HoaDon mn = new HoaDon();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_giamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giamActionPerformed
        // TODO add your handling code here:
        if(btn_giam.getText().equalsIgnoreCase("Giảm Giá")){
            btn_giam.setText("Hủy");
            btn_tang.setText("Lưu");
            btn_thoat.setEnabled(false);
        }
        else if(btn_giam.getText().equalsIgnoreCase("Lưu")){
            int pt = 0;
            try{
                pt=Integer.parseInt(txt_pt.getText());
            }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số","Thong bao",JOptionPane.ERROR_MESSAGE);
                    txt_pt.requestFocus();
                    txt_pt.selectAll();
                    return;
            }if(pt<1 || pt >100){
                JOptionPane.showMessageDialog(null, "Tỷ lệ % tối thiểu là 1% hoặc tối đa là 100%","Thong bao",JOptionPane.ERROR_MESSAGE);
                txt_pt.requestFocus();
                txt_pt.selectAll();
                return ;
            }else{               
                if (kt_tt(cb_msp.getSelectedItem().toString())) {                
                    long dg_cu = getDg(cb_msp.getSelectedItem().toString());
                    float dg_moi = (float) Math.floor(dg_cu + (dg_cu * (pt / 100.0f)) + 0.5f);
                    String sql = "update hdn set dg='" + dg_moi + "' where ma_sp='" + cb_msp.getSelectedItem().toString() + "'";
                    DBManager.Update(sql);
                    JOptionPane.showMessageDialog(null, "Cập nhật thành công", "Thong bao", JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(null, " Giá Cũ = " + dg_cu + "\nGiá Mới = " + dg_moi, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Hiện tại sản phẩm này chưa có hàng", "Thông báo", JOptionPane.ERROR_MESSAGE);
                } 
            }
        }
        else{
            btn_tang.setText("Tăng Giá");
            btn_giam.setText("Giảm Giá");
            btn_thoat.setEnabled(true);            
        }        
    }//GEN-LAST:event_btn_giamActionPerformed

    private void btn_tangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tangActionPerformed
        // TODO add your handling code here:
        if(btn_tang.getText().equalsIgnoreCase("Tăng Giá")){
            btn_tang.setText("Hủy");
            btn_giam.setText("Lưu");
            btn_thoat.setEnabled(false);
        }
        else if(btn_tang.getText().equalsIgnoreCase("Lưu")){
   int pt = 0;
            try{
                pt=Integer.parseInt(txt_pt.getText());
            }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số","Thong bao",JOptionPane.ERROR_MESSAGE);
                    txt_pt.requestFocus();
                    txt_pt.selectAll();
                    return;
            }if(pt<1 || pt >100){
                JOptionPane.showMessageDialog(null, "Tỷ lệ % tối thiểu là 1% hoặc tối đa là 100%","Thong bao",JOptionPane.ERROR_MESSAGE);
                txt_pt.requestFocus();
                txt_pt.selectAll();
                return ;
            }else{
                if (kt_tt(cb_msp.getSelectedItem().toString())) {                
                    long dg_cu = getDg(cb_msp.getSelectedItem().toString());
                    float dg_moi = (float) Math.floor(dg_cu - (dg_cu * (pt / 100.0f)) + 0.5f);

                    String sql = "update hdn set dg='" + dg_moi + "' where ma_sp='" + cb_msp.getSelectedItem().toString() + "'";
                    DBManager.Update(sql);
                    JOptionPane.showMessageDialog(null, "Cập nhật thành công", "Thong bao", JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(null, " Giá Cũ = " + dg_cu + "\nGiá Mới = " + dg_moi, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Hiện tại sản phẩm này chưa có hàng", "Thông báo", JOptionPane.ERROR_MESSAGE);
                } 
            }          
        }
        else{
            btn_tang.setText("Tăng Giá");
            btn_giam.setText("Giảm Giá");
            btn_thoat.setEnabled(true);            
        }
    }//GEN-LAST:event_btn_tangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThayDoiGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThayDoiGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThayDoiGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThayDoiGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThayDoiGia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_giam;
    private javax.swing.JButton btn_tang;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JComboBox<String> cb_msp;
    private javax.swing.JComboBox<String> cb_tsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_pt;
    // End of variables declaration//GEN-END:variables
}
